### PR TITLE
Implement swmm-stride using c-code

### LINKED ISSUE #500: Integrate swmm_stride for PySWMM-v2.x

### PR DESCRIPTION
**Pull request by karosc**
Closes #500

This PR makes the default `PySWMM.swmm_stride()` method reference the c-code in `swmm.toolkit.solver.swmm_stride()`

However, if a user is using swmm_toolkit < 0.15.0, the old python implementation of swmm_stride is monkey patched into the PySWMM class, keeping this version of pyswmm backwards compatible with older versions of `swmm.toolkit`

### CODE REVIEW

**Comment by karosc** [comment]
@bemcdonnell, from my point of view our next release will be 2.0. We can add to develop until we get there.

**Comment by bemcdonnell** [comment]
@karosc are we still using flake8 to lint the code?

**Review by bemcdonnell — APPROVED** [review]
@karosc I think this is good.  I'm just thinking the code needs to be linted with flake8.  It looks like there are a few function args without spaces between the arguments

**Comment by bemcdonnell** [comment]
@karosc Again, fantastic work.  I am going to make this merge into develop-v2.x branch.

**Pull request merged**
